# Generated by Django 4.0 on 2022-01-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('essn', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fimg', models.ImageField(upload_to='./static/img/')),
                ('degree', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('isteacher', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('essn', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fimg', models.ImageField(upload_to='./static/img/')),
                ('degree', models.TextField()),
                ('isverified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('sem', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=40)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.teacher')),
            ],
        ),
    ]
