# Generated by Django 4.0 on 2022-01-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='fimg',
            field=models.ImageField(upload_to='Faculty/static/img/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fimg',
            field=models.ImageField(upload_to='Faculty/static/img/'),
        ),
    ]
