# Generated by Django 4.0 on 2022-01-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0006_alter_hod_fimg_alter_teacher_fimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='fimg',
            field=models.ImageField(upload_to='./Faculty/static/Faculty/img/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fimg',
            field=models.ImageField(upload_to='./Faculty/static/Faculty/img/'),
        ),
    ]
