# Generated by Django 4.0 on 2022-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0008_alter_hod_essn_alter_hod_fimg_alter_teacher_essn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='fimg',
            field=models.ImageField(upload_to='./static/Faculty/img'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fimg',
            field=models.ImageField(upload_to='./static/Faculty/img'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='section',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=10),
        ),
    ]
