# Generated by Django 4.0 on 2022-01-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0009_alter_hod_fimg_alter_teacher_fimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaches',
            name='section',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='sem',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], default=None, max_length=10),
        ),
    ]
