# Generated by Django 4.0 on 2022-01-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0011_alter_teaches_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], default=None, max_length=10)),
                ('sem', models.CharField(choices=[('1', '1st sem'), ('2', '2nd sem'), ('3', '3rd sem'), ('4', '4th sem'), ('5', '5th sem'), ('6', '6th sem'), ('7', '7th sem'), ('8', '8th sem')], default=None, max_length=10)),
                ('teacher', models.ForeignKey(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], on_delete=django.db.models.deletion.CASCADE, to='Faculty.teacher')),
            ],
        ),
    ]
