# Generated by Django 4.0 on 2022-01-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0014_alter_classteacher_section_alter_classteacher_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaches',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
