# Generated by Django 4.0 on 2022-01-18 08:36

import Faculty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0017_alter_teaches_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(default=None, upload_to='assignments/'),
        ),
    ]
