# Generated by Django 4.0 on 2022-01-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0022_assignment_section_assignment_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='sem',
        ),
    ]
