# Generated by Django 4.0 on 2022-01-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0023_remove_assignment_section_remove_assignment_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sem',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
