# Generated by Django 4.0 on 2022-01-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0024_assignment_section_assignment_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(default=None, upload_to='assignments/pdf/'),
        ),
    ]
