# Generated by Django 4.0 on 2022-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0025_alter_assignment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(upload_to='assignments/pdf/'),
        ),
    ]
