# Generated by Django 4.0 on 2022-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='simg',
            field=models.ImageField(default=None, upload_to='./static/student/img'),
        ),
    ]
