# Generated by Django 4.0 on 2022-01-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_student_classteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
    ]
