# Generated by Django 4.0 on 2022-01-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cycle',
            field=models.CharField(choices=[('1', 'None'), ('2', 'Physics'), ('3', 'Chemistry')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='simg',
            field=models.ImageField(upload_to='./static/student/img'),
        ),
    ]
