# Generated by Django 4.0 on 2022-01-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0011_alter_teaches_sem'),
        ('Student', '0008_alter_student_cycle_alter_student_simg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classTeacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculty.teacher'),
        ),
    ]
