# Generated by Django 4.0 on 2022-01-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_alter_student_simg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='simg',
            field=models.ImageField(upload_to='static/Student/img'),
        ),
    ]
